<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-23 at 18:05:01.
 * @ignore phpUnit Test Class
 */
class variableCaseChangerTest extends PHPUnit_Framework_TestCase {

  /**
   * @var variableCaseChanger
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new variableCaseChanger;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  

}
