<?php

include_once '../src/convention/tConvention.trait.php';
include_once '../src/convention/camelCaseB.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-26 at 02:03:47.
 * @ignore phpUnit Test Class
 */
class camelCaseBTest extends PHPUnit_Framework_TestCase {

  /**
   * @var camelCaseB
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    //$this->object = new camelCaseA;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  protected $_WordArray = ['This', 'is', 'a', 'word', 'array'];
  
  public function testConstruct() {
    $this->object = camelCaseB::fromWordArray([]);
    $this->assertInstanceOf(
            'camelCaseB',
            $this->object,
            'construct Failed');
  }
  
  /**
   * @covers camelCaseB::toString
   * @covers camelCaseB::fromWordArray($vWordArray)
   */
  public function testToString() {
    
    $this->object = camelCaseB::fromWordArray($this->_WordArray);
    
    $this->assertEquals(
            'ThisIsAWordArray',
            $this->object->toString(),
            'Convention Conversion Failed');
    
  }

}
