<?php

include_once '../src/convention/convention.class.php';
include_once '../src/convention/camelCaseA.class.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-08-26 at 02:03:47.
 */
class camelCaseATest extends PHPUnit_Framework_TestCase {

  /**
   * @var camelCaseA
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    //$this->object = new camelCaseA;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {
    
  }
  
  public function testConstruct() {
    $this->object = camelCaseA::fromWordArray([]);
    $this->assertInstanceOf(
            'camelCaseA',
            $this->object,
            'new self() loaded base class');
  }

  /**
   * @covers camelCaseA::toString
   * @todo   Implement testToString().
   */
  public function testToString() {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
            'This test has not been implemented yet.'
    );
  }

}
